### PR TITLE
Set headers in main thread from another thread if no value has been set yet.

### LINKED ISSUE #219: Token authorization broken in 4.1
After upgrading from 4.0.0 to 4.1.0 our token authorization stopped to work.
We use a piece of code almost identical to the manual:

``` (ruby)
class Customer < ActiveResource::Base
  self.site = CONFIG[:site]
  self.prefix = '/api/v1/'
  headers['Authorization'] = "Token token=\"#{Authenticator.current_token}\""
end
```

with `Authenticator` being:

``` (ruby)
class Authenticator
  def self.current_token
    if CONFIG[:token].blank?
      params = {'user' => CONFIG[:user], 'password' =>CONFIG[:password]}.to_json
      url = CONFIG[:site] + '/authorization/api/v1/login'
      uri = URI.parse(url)
      result = ''
      if uri.scheme == 'https'
        Net::HTTP.start(uri.host, uri.port,
                        use_ssl: true,
                        verify_mode: OpenSSL::SSL::VERIFY_NONE) do |http|
          result = handle_request(http, uri, params)
        end
      else
        Net::HTTP.start(uri.host, uri.port) do |http|
          result = handle_request(http, uri, params)
        end
      end
      CONFIG[:token] = result['token']
    end
    CONFIG[:token]
  end

  class << self
    private

    def handle_request(http, uri, params)
      # http.open_timeout = @config.http_open_timeout
      # http.read_timeout = @config.http_read_timeout

      request = Net::HTTP::Post.new(uri.path, 'Content-Type' => 'application/json')
      request.body = params
      response = http.request request

      case response
        when Net::HTTPSuccess then
          JSON.parse(response.body)
        when Net::HTTPUnauthorized then
          raise 'Unauthorized'
        else
          raise
      end
    end
  end
end
```

After a server start the token will be acquired and sometimes the first call will even have a token. All subsequent calls are missing the token header. Going back to 4.0.0 will fix this issue immediately. Do you need any further data?

### PR DESCRIPTION
**Pull request by bernardoamc**
Fixes #219 

The current behaviour sets an empty Hash for headers in the main thread, but we should get the value from another thread if the main thread doesn't have a value in its headers.

This happens because when we do this:

```ruby
# lib/active_resource/base.rb#L655
self._headers ||= {}
```

We will trigger:

```ruby
# lib/active_resource/threadsafe_attributes.rb#L41
unless threadsafe_attribute_defined_by_thread?(name, main_thread)
  set_threadsafe_attribute_by_thread(name, value, main_thread)
end
```

Which will set an empty Hash for `headers` in the main thread.

Thanks for doing all the research @repinel ! <3

### CODE REVIEW

File: lib/active_resource/base.rb [hunk 1]
```diff
@@ -652,11 +652,11 @@ def connection(refresh = false)
       end
 
       def headers
-        self._headers ||= {}
+        headers_state = self._headers || {}
         if superclass != Object && superclass.headers
```
Comment (rafaelfranca) [inline lib/active_resource/base.rb]: would not `superclass.headers` always return true? I don't see when this condition is not true.

File: lib/active_resource/base.rb [hunk 2]
```diff
@@ -652,11 +652,11 @@ def connection(refresh = false)
       end
 
       def headers
-        self._headers ||= {}
-        if superclass != Object && superclass.headers
-          self._headers = superclass.headers.merge(_headers)
+        headers_state = self._headers || {}
+        if superclass != Object
```
Comment (bernardoamc) [inline lib/active_resource/base.rb]: `superclass.headers` will return a `{}` even if it's value is not set, so it will always evaluate to `true`. Given this we can safely remove it from the conditional. @rafaelfranca 👍

**Comment by rafaelfranca** [comment]
Backported in 3d10cde

**Comment by repinel** [comment]
@bernardoamc Thanks for creating the PR ❤️
